// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Infraestructure.Data.Contexts;

namespace PetShop.Infraestructure.Data.Migrations.SqlServer
{
    [DbContext(typeof(PetShopSqlServerContext))]
    [Migration("20220210220332_v1.3")]
    partial class v13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetShop.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.OrderAggregate.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdenItems");
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.ProductAggregate.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "Lata",
                            Description = "Alimento prescrito de presentación húmeda que ayuda a la regulación de la microbiota intestinal, mejorando la salud digestiva ante enfermedades fibro-responsivas.\r\n                                Su tecnología ActivBome+ favorece la salud y bienestar del tracto digestivo al nutrir el microbioma intestinal.\r\n                                Contiene altos niveles de ácidos grasos omega 3 (EPA y DHA) que ayudan a reducir los procesos inflamatorios derivados de la enfermedad intestinal.\r\n                                Ha demostrado clínicamente que ayuda a reducir las heces líquidas en 24 horas.",
                            Image = "https://www.gabrica.co/wp-content/uploads/2020/05/11001097-hills-prescription-diet-lata-GastroBiome.png",
                            Name = "Hill’s Prescription Diet Lata GastroBiome",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 2L,
                            Code = "Synergy",
                            Description = "Indicado para ayudar la salud e higiene bucal en los perros dejando máxima blancura en los dientes.\r\n                                – Sin alcohol, sin azúcar, sin detergentes y sin sabores picantes de menta.\r\n                                – La fórmula se activa al contacto con la placa bacteriana y los gérmenes en la cavidad oral, eliminando bacterias y el mal olor causado por ellas.\r\n                                – Protege las encías y ayuda a prevenir y tratar la gingivitis.",
                            Image = "https://www.gabrica.co/wp-content/uploads/2019/04/DENTAL-FRESH-Advanced-Whitening-Perros.png",
                            Name = "Dental Fresh Advanced Whitening Perros",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 3L,
                            Code = "Calming",
                            Description = "Suplemento alimenticio para perros adultos, ayuda a reducir el estrés asociado a problemas de comportamiento como hiperactividad, agresión, control de esfínteres, rascado excesivo o destrucción.\r\n                                – Recomendado para mascotas expuestas a ambientes de estrés alto.\r\n                                – No afecta la personalidad del animal o su nivel de energía.\r\n                                – Puede ser utilizado diariamente.\r\n                                – Con Complejo Tranquilizante del Calostro, L-Teanina, Vitamina B, Lecitina y Calming derivado de plantas.",
                            Image = "https://www.gabrica.co/wp-content/uploads/2019/04/Calming-Pet-Naturals.png",
                            Name = "Calming Pet Naturals",
                            Price = 34000m
                        },
                        new
                        {
                            Id = 4L,
                            Code = "Furminator",
                            Description = "Recoge rápidamente el pelo de las mascotas para una fácil limpieza Reutilizable: tan eficaz y dura más que un rodillo adhesivo.",
                            Image = "https://www.gabrica.co/wp-content/uploads/2020/05/furminator-desechar-perro-gato.png",
                            Name = "Furminator Herramienta De Recolección De Pelos",
                            Price = 68000m
                        },
                        new
                        {
                            Id = 5L,
                            Code = "Microchip",
                            Description = "Es un dispostivo electronico que se implanta debajo de la piel de la mascota, es un metodo de idenfiticacion de la mascota, en caso de perdida, o robo.\r\n                                Contiene datos de la mascota y del propietario.\r\n                                Viene con un aplicador estéril que debe ser implantado por un medico veterinario.\r\n                                El empaque es de color amarillo, viene con el aplicador, carnet del propietario y una medalla que contiene el codigo QR para poder realizar la lectura por medio de una pagina especificada en la caja de entrega..",
                            Image = "https://www.gabrica.co/wp-content/uploads/2020/07/microchip-3.png",
                            Name = "Microchip",
                            Price = 179000m
                        },
                        new
                        {
                            Id = 6L,
                            Code = "Beeps ",
                            Description = "– Facilita el baño haciéndolo rápido y simple.\r\n                                – Contiene avena que hidrata el pelaje.\r\n                                – Indicado para gatos a partir de 4 semanas.\r\n                                Fragancia de uva.",
                            Image = "https://www.gabrica.co/wp-content/uploads/2019/04/Beeps-Champu-Hidratante-Cat-Care.png",
                            Name = "Beeps Champú Para Gatos",
                            Price = 22000m
                        });
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FullName = "Leidy Tatina",
                            Password = "123456",
                            Type = 0,
                            UserName = "leidy"
                        },
                        new
                        {
                            Id = 2L,
                            FullName = "Pepito Perez",
                            Password = "123456",
                            Type = 1,
                            UserName = "pepito"
                        });
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.HasOne("PetShop.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("PetShop.Domain.Aggregates.OrderAggregate.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetShop.Domain.Aggregates.ProductAggregate.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.ProductAggregate.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PetShop.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
